// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderingService.Dal;

#nullable disable

namespace OrderingService.Dal.Migrations
{
    [DbContext(typeof(OrderingContext))]
    [Migration("20230305214706_AddAuth")]
    partial class AddAuth
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.1.23111.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrderingService.Dal.Models.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasAlternateKey("Phone");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("851e8bb2-9498-4852-b702-242d3cef6654"),
                            FullName = "Меркушев Бенедикт Алексеевич",
                            Phone = "89996225028"
                        },
                        new
                        {
                            Id = new Guid("8f1fe072-c8cb-4a54-8001-056c0d6ba55f"),
                            FullName = "Ефимов Аким Лаврентьевич",
                            Phone = "89506225027"
                        },
                        new
                        {
                            Id = new Guid("87184d4b-bc15-43cc-9dd3-f61da3a35095"),
                            FullName = "Савин Август Оскарович",
                            Phone = "89506225026"
                        },
                        new
                        {
                            Id = new Guid("b2cfbca6-48d2-4d2c-89bb-4c609b71deab"),
                            FullName = "Воронцов Любомир Антонович",
                            Phone = "89906225025"
                        },
                        new
                        {
                            Id = new Guid("af93ed71-fb44-48fc-b9c8-2d018702bcc5"),
                            FullName = "Ларионов Аввакуум Христофорович",
                            Phone = "89506335028"
                        },
                        new
                        {
                            Id = new Guid("5721c29f-1f2e-4d02-83ff-9a3f57a817e6"),
                            FullName = "Беляков Демьян Степанович",
                            Phone = "89606225028"
                        },
                        new
                        {
                            Id = new Guid("4a57edba-bfaa-4388-860b-7e6e1ed4ba83"),
                            FullName = "Баранова Марьяна Рудольфовна",
                            Phone = "89506224428"
                        },
                        new
                        {
                            Id = new Guid("60a287dd-fea3-43fa-9d73-eaaab0e96ab8"),
                            FullName = "Зайцева Римма Аристарховна",
                            Phone = "89503335028"
                        },
                        new
                        {
                            Id = new Guid("34fa4285-beb7-4e52-bcf4-bcd99e2d5b94"),
                            FullName = "Лазарева Лигия Пётровна",
                            Phone = "89506225268"
                        },
                        new
                        {
                            Id = new Guid("c6697675-09ab-40d0-b853-f8831a989e77"),
                            FullName = "Фёдорова Асида Федоровна",
                            Phone = "89506225278"
                        },
                        new
                        {
                            Id = new Guid("d7e0d0ca-ded9-4297-806f-c0a1739cf2a3"),
                            FullName = "Дорофеева Георгина Онисимовна",
                            Phone = "89506330270"
                        });
                });

            modelBuilder.Entity("OrderingService.Dal.Models.ClientCredentials", b =>
                {
                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ClientId", "Username");

                    b.ToTable("ClientCredentials");

                    b.HasData(
                        new
                        {
                            ClientId = new Guid("851e8bb2-9498-4852-b702-242d3cef6654"),
                            Username = "user851e8bb2-9498-4852-b702-242d3cef6654",
                            Password = "qwe12345"
                        },
                        new
                        {
                            ClientId = new Guid("8f1fe072-c8cb-4a54-8001-056c0d6ba55f"),
                            Username = "user8f1fe072-c8cb-4a54-8001-056c0d6ba55f",
                            Password = "qwe12345"
                        },
                        new
                        {
                            ClientId = new Guid("87184d4b-bc15-43cc-9dd3-f61da3a35095"),
                            Username = "user87184d4b-bc15-43cc-9dd3-f61da3a35095",
                            Password = "qwe12345"
                        },
                        new
                        {
                            ClientId = new Guid("b2cfbca6-48d2-4d2c-89bb-4c609b71deab"),
                            Username = "userb2cfbca6-48d2-4d2c-89bb-4c609b71deab",
                            Password = "qwe12345"
                        },
                        new
                        {
                            ClientId = new Guid("af93ed71-fb44-48fc-b9c8-2d018702bcc5"),
                            Username = "useraf93ed71-fb44-48fc-b9c8-2d018702bcc5",
                            Password = "qwe12345"
                        },
                        new
                        {
                            ClientId = new Guid("5721c29f-1f2e-4d02-83ff-9a3f57a817e6"),
                            Username = "user5721c29f-1f2e-4d02-83ff-9a3f57a817e6",
                            Password = "qwe12345"
                        },
                        new
                        {
                            ClientId = new Guid("4a57edba-bfaa-4388-860b-7e6e1ed4ba83"),
                            Username = "user4a57edba-bfaa-4388-860b-7e6e1ed4ba83",
                            Password = "qwe12345"
                        },
                        new
                        {
                            ClientId = new Guid("60a287dd-fea3-43fa-9d73-eaaab0e96ab8"),
                            Username = "user60a287dd-fea3-43fa-9d73-eaaab0e96ab8",
                            Password = "qwe12345"
                        },
                        new
                        {
                            ClientId = new Guid("34fa4285-beb7-4e52-bcf4-bcd99e2d5b94"),
                            Username = "user34fa4285-beb7-4e52-bcf4-bcd99e2d5b94",
                            Password = "qwe12345"
                        },
                        new
                        {
                            ClientId = new Guid("c6697675-09ab-40d0-b853-f8831a989e77"),
                            Username = "userc6697675-09ab-40d0-b853-f8831a989e77",
                            Password = "qwe12345"
                        },
                        new
                        {
                            ClientId = new Guid("d7e0d0ca-ded9-4297-806f-c0a1739cf2a3"),
                            Username = "userd7e0d0ca-ded9-4297-806f-c0a1739cf2a3",
                            Password = "qwe12345"
                        });
                });

            modelBuilder.Entity("OrderingService.Dal.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2023, 3, 5, 21, 47, 6, 509, DateTimeKind.Utc).AddTicks(208));

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6b6016dc-ec6e-4dff-a0a9-fb5ac1c8161b"),
                            ClientId = new Guid("851e8bb2-9498-4852-b702-242d3cef6654"),
                            CreatedAt = new DateTime(2022, 11, 25, 21, 47, 4, 720, DateTimeKind.Utc).AddTicks(8813)
                        },
                        new
                        {
                            Id = new Guid("d311cb52-1729-40aa-8277-54d89d3bd17a"),
                            ClientId = new Guid("8f1fe072-c8cb-4a54-8001-056c0d6ba55f"),
                            CreatedAt = new DateTime(2022, 5, 9, 21, 47, 4, 721, DateTimeKind.Utc).AddTicks(155)
                        },
                        new
                        {
                            Id = new Guid("65d5510a-a600-4b1b-b1f5-debc5316b2a0"),
                            ClientId = new Guid("d7e0d0ca-ded9-4297-806f-c0a1739cf2a3"),
                            CreatedAt = new DateTime(2023, 11, 7, 21, 47, 4, 721, DateTimeKind.Utc).AddTicks(168)
                        },
                        new
                        {
                            Id = new Guid("a31861b0-3732-40d3-b2ca-9999f63c7662"),
                            ClientId = new Guid("c6697675-09ab-40d0-b853-f8831a989e77"),
                            CreatedAt = new DateTime(2024, 3, 29, 21, 47, 4, 721, DateTimeKind.Utc).AddTicks(171)
                        },
                        new
                        {
                            Id = new Guid("df96aae7-ff70-4005-83ff-cc19da3e6e0a"),
                            ClientId = new Guid("4a57edba-bfaa-4388-860b-7e6e1ed4ba83"),
                            CreatedAt = new DateTime(2022, 5, 26, 21, 47, 4, 721, DateTimeKind.Utc).AddTicks(172)
                        },
                        new
                        {
                            Id = new Guid("dd20ffe8-4ab1-46b6-a32b-ff14d4b09170"),
                            ClientId = new Guid("8f1fe072-c8cb-4a54-8001-056c0d6ba55f"),
                            CreatedAt = new DateTime(2023, 4, 17, 21, 47, 4, 721, DateTimeKind.Utc).AddTicks(176)
                        },
                        new
                        {
                            Id = new Guid("6ff684fa-bf85-47bf-b78b-f1e9f25dc976"),
                            ClientId = new Guid("8f1fe072-c8cb-4a54-8001-056c0d6ba55f"),
                            CreatedAt = new DateTime(2023, 1, 20, 21, 47, 4, 721, DateTimeKind.Utc).AddTicks(178)
                        },
                        new
                        {
                            Id = new Guid("bb27cab5-5938-4ae1-8a0d-cddad6f86eb5"),
                            ClientId = new Guid("87184d4b-bc15-43cc-9dd3-f61da3a35095"),
                            CreatedAt = new DateTime(2024, 1, 2, 21, 47, 4, 721, DateTimeKind.Utc).AddTicks(180)
                        },
                        new
                        {
                            Id = new Guid("092d65c8-2309-4cd0-888d-fb0bdbf787d4"),
                            ClientId = new Guid("c6697675-09ab-40d0-b853-f8831a989e77"),
                            CreatedAt = new DateTime(2022, 3, 17, 21, 47, 4, 721, DateTimeKind.Utc).AddTicks(181)
                        },
                        new
                        {
                            Id = new Guid("d139c831-dae3-49f2-8008-5d4498978b9e"),
                            ClientId = new Guid("d7e0d0ca-ded9-4297-806f-c0a1739cf2a3"),
                            CreatedAt = new DateTime(2024, 3, 4, 21, 47, 4, 721, DateTimeKind.Utc).AddTicks(184)
                        },
                        new
                        {
                            Id = new Guid("3bd6ada7-67c7-42fc-a535-b987c21bb673"),
                            ClientId = new Guid("87184d4b-bc15-43cc-9dd3-f61da3a35095"),
                            CreatedAt = new DateTime(2022, 3, 25, 21, 47, 4, 721, DateTimeKind.Utc).AddTicks(187)
                        },
                        new
                        {
                            Id = new Guid("cf275dd4-0cdc-433e-aaa3-d754300cf486"),
                            ClientId = new Guid("5721c29f-1f2e-4d02-83ff-9a3f57a817e6"),
                            CreatedAt = new DateTime(2024, 2, 23, 21, 47, 4, 721, DateTimeKind.Utc).AddTicks(189)
                        },
                        new
                        {
                            Id = new Guid("cad06823-eb93-4370-a8f6-3b8005a91f13"),
                            ClientId = new Guid("34fa4285-beb7-4e52-bcf4-bcd99e2d5b94"),
                            CreatedAt = new DateTime(2022, 7, 19, 21, 47, 4, 721, DateTimeKind.Utc).AddTicks(190)
                        },
                        new
                        {
                            Id = new Guid("58516434-b850-466a-afb1-d4beb20b070f"),
                            ClientId = new Guid("34fa4285-beb7-4e52-bcf4-bcd99e2d5b94"),
                            CreatedAt = new DateTime(2022, 12, 18, 21, 47, 4, 721, DateTimeKind.Utc).AddTicks(192)
                        },
                        new
                        {
                            Id = new Guid("d342f791-7303-43d1-8e44-c43b34628330"),
                            ClientId = new Guid("34fa4285-beb7-4e52-bcf4-bcd99e2d5b94"),
                            CreatedAt = new DateTime(2023, 4, 7, 21, 47, 4, 721, DateTimeKind.Utc).AddTicks(194)
                        },
                        new
                        {
                            Id = new Guid("a3db2e0b-fed6-4a26-9535-4a2ddbab77d0"),
                            ClientId = new Guid("b2cfbca6-48d2-4d2c-89bb-4c609b71deab"),
                            CreatedAt = new DateTime(2024, 2, 24, 21, 47, 4, 721, DateTimeKind.Utc).AddTicks(195)
                        },
                        new
                        {
                            Id = new Guid("edc81d57-3e1e-4e56-b3b5-b72dfb03e79a"),
                            ClientId = new Guid("4a57edba-bfaa-4388-860b-7e6e1ed4ba83"),
                            CreatedAt = new DateTime(2022, 9, 25, 21, 47, 4, 721, DateTimeKind.Utc).AddTicks(197)
                        },
                        new
                        {
                            Id = new Guid("8d1602ca-63f3-45ee-b3af-e33e2d9145fa"),
                            ClientId = new Guid("d7e0d0ca-ded9-4297-806f-c0a1739cf2a3"),
                            CreatedAt = new DateTime(2023, 5, 22, 21, 47, 4, 721, DateTimeKind.Utc).AddTicks(199)
                        },
                        new
                        {
                            Id = new Guid("ab0bae64-223f-477f-9dae-33876f6efb2d"),
                            ClientId = new Guid("c6697675-09ab-40d0-b853-f8831a989e77"),
                            CreatedAt = new DateTime(2023, 11, 29, 21, 47, 4, 721, DateTimeKind.Utc).AddTicks(202)
                        },
                        new
                        {
                            Id = new Guid("b8c709c8-3d09-4442-aa3c-eecc9d92ef84"),
                            ClientId = new Guid("b2cfbca6-48d2-4d2c-89bb-4c609b71deab"),
                            CreatedAt = new DateTime(2023, 7, 25, 21, 47, 4, 721, DateTimeKind.Utc).AddTicks(204)
                        },
                        new
                        {
                            Id = new Guid("73d13147-917f-4187-94ff-2330622fa4e1"),
                            ClientId = new Guid("60a287dd-fea3-43fa-9d73-eaaab0e96ab8"),
                            CreatedAt = new DateTime(2022, 7, 17, 21, 47, 4, 721, DateTimeKind.Utc).AddTicks(205)
                        },
                        new
                        {
                            Id = new Guid("ba057d6f-7ed3-4751-8b9c-ec4ccee42a31"),
                            ClientId = new Guid("b2cfbca6-48d2-4d2c-89bb-4c609b71deab"),
                            CreatedAt = new DateTime(2022, 10, 24, 21, 47, 4, 721, DateTimeKind.Utc).AddTicks(207)
                        });
                });

            modelBuilder.Entity("OrderingService.Dal.Models.OrderProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductsInOrders", t =>
                        {
                            t.HasCheckConstraint("Price", "Price > 0");

                            t.HasCheckConstraint("Quantity", "Quantity >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("20f481a1-ca12-4dfe-8a5b-d001252ec79c"),
                            OrderId = new Guid("6b6016dc-ec6e-4dff-a0a9-fb5ac1c8161b"),
                            Price = 5097m,
                            ProductId = new Guid("c81d2b57-ee83-4419-a204-2a6c547d59dd"),
                            Quantity = 3
                        },
                        new
                        {
                            Id = new Guid("a856dcc7-765d-42de-9410-8e2e5b8de730"),
                            OrderId = new Guid("6b6016dc-ec6e-4dff-a0a9-fb5ac1c8161b"),
                            Price = 11599.98m,
                            ProductId = new Guid("ef9f969e-9374-4fda-872c-f3614bfa46ca"),
                            Quantity = 2
                        },
                        new
                        {
                            Id = new Guid("65b1099f-75a9-4db7-b978-d1ed0be73a92"),
                            OrderId = new Guid("d311cb52-1729-40aa-8277-54d89d3bd17a"),
                            Price = 45597m,
                            ProductId = new Guid("54404b97-fa8f-44c7-9668-34833699c01f"),
                            Quantity = 3
                        },
                        new
                        {
                            Id = new Guid("711fb9a4-eb44-4bc6-a88a-acf68cf25a13"),
                            OrderId = new Guid("d311cb52-1729-40aa-8277-54d89d3bd17a"),
                            Price = 197999.96m,
                            ProductId = new Guid("35261c3a-8f69-4820-9402-a5119a8425ba"),
                            Quantity = 4
                        },
                        new
                        {
                            Id = new Guid("5075a2e4-b75a-43af-97ae-5514343438c5"),
                            OrderId = new Guid("d311cb52-1729-40aa-8277-54d89d3bd17a"),
                            Price = 100m,
                            ProductId = new Guid("887bb68c-0914-4724-b52f-65317ccd0dd2"),
                            Quantity = 2
                        },
                        new
                        {
                            Id = new Guid("fd263581-9d83-4d79-99a9-7426a8e46fef"),
                            OrderId = new Guid("65d5510a-a600-4b1b-b1f5-debc5316b2a0"),
                            Price = 270122.00m,
                            ProductId = new Guid("81ed137c-acbc-49ce-9c24-8e509035ea9a"),
                            Quantity = 4
                        },
                        new
                        {
                            Id = new Guid("0abbf199-5fb8-4ae6-abc6-18c9a0d30f48"),
                            OrderId = new Guid("a31861b0-3732-40d3-b2ca-9999f63c7662"),
                            Price = 799.96m,
                            ProductId = new Guid("e2824192-935e-49c8-9f94-fc0f3decf7f8"),
                            Quantity = 4
                        },
                        new
                        {
                            Id = new Guid("07e9c8fe-a041-486d-b5b7-77bdd3cd7a3b"),
                            OrderId = new Guid("a31861b0-3732-40d3-b2ca-9999f63c7662"),
                            Price = 3196m,
                            ProductId = new Guid("e0674811-953d-44df-abda-eb0a70510739"),
                            Quantity = 4
                        },
                        new
                        {
                            Id = new Guid("dcba3f24-fa50-4d20-a6f0-705637cb3f30"),
                            OrderId = new Guid("df96aae7-ff70-4005-83ff-cc19da3e6e0a"),
                            Price = 1598m,
                            ProductId = new Guid("e0674811-953d-44df-abda-eb0a70510739"),
                            Quantity = 2
                        },
                        new
                        {
                            Id = new Guid("11b88cde-4239-45e0-a048-95de8de17ba2"),
                            OrderId = new Guid("df96aae7-ff70-4005-83ff-cc19da3e6e0a"),
                            Price = 799.96m,
                            ProductId = new Guid("1e40750f-4ecd-4311-94c2-4ea162371572"),
                            Quantity = 4
                        },
                        new
                        {
                            Id = new Guid("ec7870f9-7161-4e82-9945-b4d3347e2a8e"),
                            OrderId = new Guid("dd20ffe8-4ab1-46b6-a32b-ff14d4b09170"),
                            Price = 3398m,
                            ProductId = new Guid("c81d2b57-ee83-4419-a204-2a6c547d59dd"),
                            Quantity = 2
                        },
                        new
                        {
                            Id = new Guid("433c0590-7305-4898-b71d-a5a99dfbad30"),
                            OrderId = new Guid("6ff684fa-bf85-47bf-b78b-f1e9f25dc976"),
                            Price = 247499.95m,
                            ProductId = new Guid("35261c3a-8f69-4820-9402-a5119a8425ba"),
                            Quantity = 5
                        },
                        new
                        {
                            Id = new Guid("76646481-77ab-44e2-8f32-e1a185455459"),
                            OrderId = new Guid("bb27cab5-5938-4ae1-8a0d-cddad6f86eb5"),
                            Price = 398m,
                            ProductId = new Guid("6930d738-702f-471a-9bf5-8090af76d64b"),
                            Quantity = 2
                        },
                        new
                        {
                            Id = new Guid("96626498-2638-4437-b27e-75f7530888e7"),
                            OrderId = new Guid("bb27cab5-5938-4ae1-8a0d-cddad6f86eb5"),
                            Price = 197999.96m,
                            ProductId = new Guid("35261c3a-8f69-4820-9402-a5119a8425ba"),
                            Quantity = 4
                        },
                        new
                        {
                            Id = new Guid("cc7087fb-65de-4a0c-801a-5328fee3f14f"),
                            OrderId = new Guid("092d65c8-2309-4cd0-888d-fb0bdbf787d4"),
                            Price = 77499.95m,
                            ProductId = new Guid("35594658-80d7-44fa-b7b4-1e553dd0c014"),
                            Quantity = 5
                        },
                        new
                        {
                            Id = new Guid("c5389f46-37cf-4a00-9cf6-d8397cc691cd"),
                            OrderId = new Guid("d139c831-dae3-49f2-8008-5d4498978b9e"),
                            Price = 98999.98m,
                            ProductId = new Guid("35261c3a-8f69-4820-9402-a5119a8425ba"),
                            Quantity = 2
                        },
                        new
                        {
                            Id = new Guid("af86fca6-9aeb-41a7-89ed-a2c06779f15f"),
                            OrderId = new Guid("d139c831-dae3-49f2-8008-5d4498978b9e"),
                            Price = 258495m,
                            ProductId = new Guid("eb3a550f-f4ed-4836-8362-b55fc41da63a"),
                            Quantity = 5
                        },
                        new
                        {
                            Id = new Guid("887a1ce7-16e8-44a3-9c80-df65a57cf48c"),
                            OrderId = new Guid("d139c831-dae3-49f2-8008-5d4498978b9e"),
                            Price = 750m,
                            ProductId = new Guid("25a9ca45-fdef-4f7f-889b-743ec5d1cd64"),
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("7b14f92d-3407-43d3-8bad-7b2e32977043"),
                            OrderId = new Guid("3bd6ada7-67c7-42fc-a535-b987c21bb673"),
                            Price = 3995m,
                            ProductId = new Guid("e0674811-953d-44df-abda-eb0a70510739"),
                            Quantity = 5
                        },
                        new
                        {
                            Id = new Guid("31e9e5a5-ccf0-433c-9ef7-14589f975632"),
                            OrderId = new Guid("3bd6ada7-67c7-42fc-a535-b987c21bb673"),
                            Price = 199.99m,
                            ProductId = new Guid("e2824192-935e-49c8-9f94-fc0f3decf7f8"),
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("65b8be63-1bbe-40c4-9c8e-0a050c351e2f"),
                            OrderId = new Guid("3bd6ada7-67c7-42fc-a535-b987c21bb673"),
                            Price = 995m,
                            ProductId = new Guid("6930d738-702f-471a-9bf5-8090af76d64b"),
                            Quantity = 5
                        },
                        new
                        {
                            Id = new Guid("c8923a35-0767-4cf6-89ad-ec5242049242"),
                            OrderId = new Guid("cf275dd4-0cdc-433e-aaa3-d754300cf486"),
                            Price = 199.99m,
                            ProductId = new Guid("e2824192-935e-49c8-9f94-fc0f3decf7f8"),
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("802e891b-d51c-4dbd-a94c-4e4e0ea6802d"),
                            OrderId = new Guid("cf275dd4-0cdc-433e-aaa3-d754300cf486"),
                            Price = 17099.7m,
                            ProductId = new Guid("1917cbd5-5bac-445a-82fa-0ecd9d8c7d78"),
                            Quantity = 3
                        },
                        new
                        {
                            Id = new Guid("43ae5f58-5512-49ad-b237-1e1d6f5f2636"),
                            OrderId = new Guid("58516434-b850-466a-afb1-d4beb20b070f"),
                            Price = 250m,
                            ProductId = new Guid("887bb68c-0914-4724-b52f-65317ccd0dd2"),
                            Quantity = 5
                        },
                        new
                        {
                            Id = new Guid("1d92ca73-f574-4cbb-becf-df06c4eaf65d"),
                            OrderId = new Guid("58516434-b850-466a-afb1-d4beb20b070f"),
                            Price = 599.97m,
                            ProductId = new Guid("1e40750f-4ecd-4311-94c2-4ea162371572"),
                            Quantity = 3
                        },
                        new
                        {
                            Id = new Guid("c01e7d2c-7a22-4566-859f-9661ac1dc6d3"),
                            OrderId = new Guid("58516434-b850-466a-afb1-d4beb20b070f"),
                            Price = 15165m,
                            ProductId = new Guid("9de07e25-623f-4c74-b28c-a9afcd4c9ecd"),
                            Quantity = 5
                        },
                        new
                        {
                            Id = new Guid("6343eae5-b43d-466b-bce9-9ab31028ac6b"),
                            OrderId = new Guid("d342f791-7303-43d1-8e44-c43b34628330"),
                            Price = 3995m,
                            ProductId = new Guid("e0674811-953d-44df-abda-eb0a70510739"),
                            Quantity = 5
                        },
                        new
                        {
                            Id = new Guid("e718e903-f2a3-43e2-8c8e-ef9733c17061"),
                            OrderId = new Guid("d342f791-7303-43d1-8e44-c43b34628330"),
                            Price = 2250m,
                            ProductId = new Guid("25a9ca45-fdef-4f7f-889b-743ec5d1cd64"),
                            Quantity = 3
                        },
                        new
                        {
                            Id = new Guid("79203193-a75b-4a38-9e18-28d14d35b99c"),
                            OrderId = new Guid("d342f791-7303-43d1-8e44-c43b34628330"),
                            Price = 995m,
                            ProductId = new Guid("6930d738-702f-471a-9bf5-8090af76d64b"),
                            Quantity = 5
                        },
                        new
                        {
                            Id = new Guid("9f27a547-bbf3-4e92-9dea-5f0d1777f2f1"),
                            OrderId = new Guid("a3db2e0b-fed6-4a26-9535-4a2ddbab77d0"),
                            Price = 5097m,
                            ProductId = new Guid("c81d2b57-ee83-4419-a204-2a6c547d59dd"),
                            Quantity = 3
                        },
                        new
                        {
                            Id = new Guid("179aef14-1867-4aa1-bfc7-ada9a8b8293a"),
                            OrderId = new Guid("a3db2e0b-fed6-4a26-9535-4a2ddbab77d0"),
                            Price = 51699m,
                            ProductId = new Guid("eb3a550f-f4ed-4836-8362-b55fc41da63a"),
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("cce2f613-23c6-45d8-b0ed-0e1e5856ebdd"),
                            OrderId = new Guid("a3db2e0b-fed6-4a26-9535-4a2ddbab77d0"),
                            Price = 398m,
                            ProductId = new Guid("6930d738-702f-471a-9bf5-8090af76d64b"),
                            Quantity = 2
                        },
                        new
                        {
                            Id = new Guid("5e516f11-1262-4df7-90fa-3a756aa7cb34"),
                            OrderId = new Guid("edc81d57-3e1e-4e56-b3b5-b72dfb03e79a"),
                            Price = 799.96m,
                            ProductId = new Guid("e2824192-935e-49c8-9f94-fc0f3decf7f8"),
                            Quantity = 4
                        },
                        new
                        {
                            Id = new Guid("6db2e2aa-da89-424b-9eda-8d88932a9b0b"),
                            OrderId = new Guid("ab0bae64-223f-477f-9dae-33876f6efb2d"),
                            Price = 199.99m,
                            ProductId = new Guid("e2824192-935e-49c8-9f94-fc0f3decf7f8"),
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("f212b069-eaa4-42ce-a7bd-545d83906fe2"),
                            OrderId = new Guid("ab0bae64-223f-477f-9dae-33876f6efb2d"),
                            Price = 4796m,
                            ProductId = new Guid("fcf85a09-83e9-4901-b69a-96054fbd21bf"),
                            Quantity = 4
                        },
                        new
                        {
                            Id = new Guid("7c436d75-e700-4377-bcda-002332ae9de9"),
                            OrderId = new Guid("ab0bae64-223f-477f-9dae-33876f6efb2d"),
                            Price = 199.99m,
                            ProductId = new Guid("e2824192-935e-49c8-9f94-fc0f3decf7f8"),
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("6cd0c651-5768-45d2-b07f-82c2cea313cd"),
                            OrderId = new Guid("b8c709c8-3d09-4442-aa3c-eecc9d92ef84"),
                            Price = 3196m,
                            ProductId = new Guid("e0674811-953d-44df-abda-eb0a70510739"),
                            Quantity = 4
                        },
                        new
                        {
                            Id = new Guid("8b231d2b-86b7-4e87-a6e3-58e1c355c04b"),
                            OrderId = new Guid("ba057d6f-7ed3-4751-8b9c-ec4ccee42a31"),
                            Price = 2398m,
                            ProductId = new Guid("fcf85a09-83e9-4901-b69a-96054fbd21bf"),
                            Quantity = 2
                        },
                        new
                        {
                            Id = new Guid("af29d2b4-f0e9-429c-b637-4893ccd8bce5"),
                            OrderId = new Guid("ba057d6f-7ed3-4751-8b9c-ec4ccee42a31"),
                            Price = 12132m,
                            ProductId = new Guid("9de07e25-623f-4c74-b28c-a9afcd4c9ecd"),
                            Quantity = 4
                        });
                });

            modelBuilder.Entity("OrderingService.Dal.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductTypeRefId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("Name");

                    b.HasIndex("ProductTypeRefId");

                    b.ToTable("Products", t =>
                        {
                            t.HasCheckConstraint("Price", "Price > 0")
                                .HasName("Price1");

                            t.HasCheckConstraint("Quantity", "Quantity >= 0")
                                .HasName("Quantity1");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("81ed137c-acbc-49ce-9c24-8e509035ea9a"),
                            Name = "IPhone 8s",
                            Price = 67530.50m,
                            ProductTypeRefId = 0,
                            Quantity = 12
                        },
                        new
                        {
                            Id = new Guid("eb3a550f-f4ed-4836-8362-b55fc41da63a"),
                            Name = "ASUS VivoBook 16X M1603QA",
                            Price = 51699m,
                            ProductTypeRefId = 0,
                            Quantity = 11
                        },
                        new
                        {
                            Id = new Guid("54404b97-fa8f-44c7-9668-34833699c01f"),
                            Name = "LED Harper 43F660Y",
                            Price = 15199m,
                            ProductTypeRefId = 0,
                            Quantity = 6
                        },
                        new
                        {
                            Id = new Guid("29d2e7b0-d807-4be7-9fe0-49d0c9258db8"),
                            Name = "LET Prestigio PTV50SS08X",
                            Price = 23199.9m,
                            ProductTypeRefId = 0,
                            Quantity = 7
                        },
                        new
                        {
                            Id = new Guid("35594658-80d7-44fa-b7b4-1e553dd0c014"),
                            Name = "AMD Ryzen 7 4700G OEM",
                            Price = 15499.99m,
                            ProductTypeRefId = 0,
                            Quantity = 20
                        },
                        new
                        {
                            Id = new Guid("1e40750f-4ecd-4311-94c2-4ea162371572"),
                            Name = "Швабра Master House Бачата",
                            Price = 199.99m,
                            ProductTypeRefId = 3,
                            Quantity = 33
                        },
                        new
                        {
                            Id = new Guid("0b0cd994-b28c-47e2-af30-e5a0d1620da2"),
                            Name = "Швабра Master House Джайв",
                            Price = 199.99m,
                            ProductTypeRefId = 3,
                            Quantity = 21
                        },
                        new
                        {
                            Id = new Guid("887bb68c-0914-4724-b52f-65317ccd0dd2"),
                            Name = "Чистящее средство для нагревательных элементов электроплит/газовых плит Topper IR 5",
                            Price = 50m,
                            ProductTypeRefId = 3,
                            Quantity = 0
                        },
                        new
                        {
                            Id = new Guid("6930d738-702f-471a-9bf5-8090af76d64b"),
                            Name = "Набор для ухода для стеклокерамических поверхностей Fiora bio ЭКО 20-002",
                            Price = 199m,
                            ProductTypeRefId = 3,
                            Quantity = 5
                        },
                        new
                        {
                            Id = new Guid("02186c64-2c0f-4044-8d73-ff9ecd93ab9a"),
                            Name = "Очиститель для тканей и мебели ОС-Гель",
                            Price = 280m,
                            ProductTypeRefId = 3,
                            Quantity = 15
                        },
                        new
                        {
                            Id = new Guid("35261c3a-8f69-4820-9402-a5119a8425ba"),
                            Name = "Газонокосилка-робот Champion RMB1828",
                            Price = 49499.99m,
                            ProductTypeRefId = 3,
                            Quantity = 8
                        },
                        new
                        {
                            Id = new Guid("e2824192-935e-49c8-9f94-fc0f3decf7f8"),
                            Name = "ТВ розетка одинарная Schneider Electric Glossa GSL000391",
                            Price = 199.99m,
                            ProductTypeRefId = 3,
                            Quantity = 20
                        },
                        new
                        {
                            Id = new Guid("1917cbd5-5bac-445a-82fa-0ecd9d8c7d78"),
                            Name = "Набор инструментов Квалитет 5027038",
                            Price = 5699.9m,
                            ProductTypeRefId = 2,
                            Quantity = 9
                        },
                        new
                        {
                            Id = new Guid("ef9f969e-9374-4fda-872c-f3614bfa46ca"),
                            Name = "Набор инструментов Swiss Tools ST-1077",
                            Price = 5799.99m,
                            ProductTypeRefId = 2,
                            Quantity = 20
                        },
                        new
                        {
                            Id = new Guid("9de07e25-623f-4c74-b28c-a9afcd4c9ecd"),
                            Name = "Набор инструментов Дело Техники 600937",
                            Price = 3033m,
                            ProductTypeRefId = 2,
                            Quantity = 30
                        },
                        new
                        {
                            Id = new Guid("be5355e6-1fd7-4598-a536-dffbde802cd6"),
                            Name = "Инструмент для вскрытия техники Rexant 12-4335",
                            Price = 99.99m,
                            ProductTypeRefId = 2,
                            Quantity = 20
                        },
                        new
                        {
                            Id = new Guid("cf2f2b98-eb5e-4276-86a6-2ddf79192f9d"),
                            Name = "Отвертка с набором насадок Matrix 11598",
                            Price = 110m,
                            ProductTypeRefId = 2,
                            Quantity = 25
                        },
                        new
                        {
                            Id = new Guid("c81d2b57-ee83-4419-a204-2a6c547d59dd"),
                            Name = "Набор инструментов КВТ Профи НИИ-09",
                            Price = 1699m,
                            ProductTypeRefId = 2,
                            Quantity = 10
                        },
                        new
                        {
                            Id = new Guid("83d895fc-bd45-49ce-906b-e523ecf2a670"),
                            Name = "Паяльная станция Rexant 12-0714",
                            Price = 4399m,
                            ProductTypeRefId = 2,
                            Quantity = 2
                        },
                        new
                        {
                            Id = new Guid("b2f29dff-dc58-467c-98ce-5ba25a631ede"),
                            Name = "Видеорегистратор 70mai Dash Cam M300",
                            Price = 3199.99m,
                            ProductTypeRefId = 1,
                            Quantity = 5
                        },
                        new
                        {
                            Id = new Guid("fcf85a09-83e9-4901-b69a-96054fbd21bf"),
                            Name = "Адаптер для скрытого подключения видеорегистратора Roadgid Cord DC",
                            Price = 1199m,
                            ProductTypeRefId = 1,
                            Quantity = 10
                        },
                        new
                        {
                            Id = new Guid("e0674811-953d-44df-abda-eb0a70510739"),
                            Name = "Камера заднего вида Silverstone F1 Interpower IP-662 LED",
                            Price = 799m,
                            ProductTypeRefId = 1,
                            Quantity = 6
                        },
                        new
                        {
                            Id = new Guid("25a9ca45-fdef-4f7f-889b-743ec5d1cd64"),
                            Name = "Инвертор DEXP CAR 150W",
                            Price = 750m,
                            ProductTypeRefId = 1,
                            Quantity = 0
                        });
                });

            modelBuilder.Entity("OrderingService.Dal.Models.ProductTypeRef", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasAlternateKey("Name");

                    b.ToTable("ProductTypes");

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Description = "Электроника",
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 1,
                            Description = "Автомобильные товары",
                            Name = "Cars"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Стройматериалы и инструменты",
                            Name = "BuildingMaterialsInstruments"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Всё для дома",
                            Name = "HouseHoldGoods"
                        });
                });

            modelBuilder.Entity("OrderingService.Dal.Models.ClientCredentials", b =>
                {
                    b.HasOne("OrderingService.Dal.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("OrderingService.Dal.Models.Order", b =>
                {
                    b.HasOne("OrderingService.Dal.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("OrderingService.Dal.Models.OrderProduct", b =>
                {
                    b.HasOne("OrderingService.Dal.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrderingService.Dal.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OrderingService.Dal.Models.Product", b =>
                {
                    b.HasOne("OrderingService.Dal.Models.ProductTypeRef", "ProductTypeRef")
                        .WithMany()
                        .HasForeignKey("ProductTypeRefId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductTypeRef");
                });
#pragma warning restore 612, 618
        }
    }
}
